name: Deploy Static Site Generator

on:
  push:
    branches:
      - main  # Change to the branch you want to deploy from

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.2'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Make main.sh executable
        run: chmod +x main.sh

      - name: Run main.sh
        run: ./main.sh

      - name: Upload public directory to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Directory where the generated site is stored
