name: Deploy Static Site Generator

on:
  push:
    branches:
      - main  # Change to the branch you want to deploy from

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to the latest version
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
          persist-credentials: false  # Disable automatic authentication

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to the latest version
        with:
          python-version: '3.12.2'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown Jinja2 pytest

      - name: List directory contents
        run: ls -la

      - name: Make main.sh executable
        run: chmod +x main.sh

      - name: Display main.sh contents
        run: cat main.sh

      - name: Run tests
        run: pytest

      - name: Run main.sh
        run: ./main.sh

      - name: Check public directory contents
        run: ls -la public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Updated to the latest version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Directory where the generated site is stored
          publish_branch: gh-pages  # Ensure deployment to gh-pages branch

